/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author fmedi
 */
public class Salida extends javax.swing.JFrame {

    /**
     * Creates new form Salida
     */
    public Salida() {
        initComponents();
        setSize(800, 300);
        setResizable(false);
        setTitle("Salida del programa");
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2_Tabla_Simbolos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2_Tabla_Error = new javax.swing.JTable();
        jLabel1_name_simbol = new javax.swing.JLabel();
        jLabel1_nameError = new javax.swing.JLabel();
        jButton1_Volver = new javax.swing.JButton();
        jButton1_archivo = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2_Tabla_Simbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Lexema", "Token"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2_Tabla_Simbolos);

        jTable2_Tabla_Error.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Token Error", "Lexema", "Línea", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2_Tabla_Error);
        if (jTable2_Tabla_Error.getColumnModel().getColumnCount() > 0) {
            jTable2_Tabla_Error.getColumnModel().getColumn(0).setResizable(false);
            jTable2_Tabla_Error.getColumnModel().getColumn(1).setResizable(false);
            jTable2_Tabla_Error.getColumnModel().getColumn(2).setResizable(false);
            jTable2_Tabla_Error.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1_name_simbol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1_name_simbol.setText("Tabla de símbolos");
        jLabel1_name_simbol.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1_nameError.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1_nameError.setText("Tabla de error");
        jLabel1_nameError.setBorder(new javax.swing.border.MatteBorder(null));

        jButton1_Volver.setText("Volver");
        jButton1_Volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_VolverActionPerformed(evt);
            }
        });

        jButton1_archivo.setText("Descargar archivo de tokens");
        jButton1_archivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_archivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1_Volver)
                            .addComponent(jButton1_archivo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1_name_simbol)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1_nameError)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_name_simbol)
                    .addComponent(jLabel1_nameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_Volver)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1_archivo))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_VolverActionPerformed
          dispose();
          new Entrada().setVisible(true);
    }//GEN-LAST:event_jButton1_VolverActionPerformed

    private void jButton1_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_archivoActionPerformed
       
       File archivo;
       PrintWriter token;
       
       archivo = new File ("C:\\Users\\fmedi\\Desktop\\archivo_de_tokens.txt");
       if(!archivo.exists()){
           JOptionPane.showMessageDialog(null, "Archivo de tokens creado");
       try{
        archivo.createNewFile();
       }catch(IOException e){ 
        JOptionPane.showMessageDialog(null, "No se ha podido crear el archivo de tokens" +e);
       }
       }else{
           JOptionPane.showMessageDialog(null, "Archivo de tokens sobreescrito");
           try {
               token = new PrintWriter(archivo,"utf-8");
               token.println("Aqui iran los tokens alv, como mandarlo? se hace despues o chamba de Sergio xd");
               token.close();
           } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
           }
           
       }
    }//GEN-LAST:event_jButton1_archivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Volver;
    private javax.swing.JButton jButton1_archivo;
    private javax.swing.JLabel jLabel1_nameError;
    private javax.swing.JLabel jLabel1_name_simbol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2_Tabla_Error;
    private javax.swing.JTable jTable2_Tabla_Simbolos;
    // End of variables declaration//GEN-END:variables
}
